--This file contains all the create script of beehive i.e. system files which is common in all the projects.
--Role setup
CREATE TABLE public.beehive_role
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
	banner character varying(20) COLLATE pg_catalog."default" NOT NULL,
	description character varying(200) COLLATE pg_catalog."default",
	is_super_admin boolean NOT NULL,
	is_active boolean NOT NULL	   
)
WITH (
    OIDS = FALSE
)
--Menu Setup
CREATE TABLE public.beehive_menu
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    banner character varying(20) COLLATE pg_catalog."default" NOT NULL,
    display_banner character varying(20) COLLATE pg_catalog."default" NOT NULL,
    icon character varying(20) COLLATE pg_catalog."default" NOT NULL,
    order_number integer NOT NULL,
    access_to_all boolean NOT NULL,
    is_dashboard_menu boolean NOT NULL,
    is_active boolean NOT NULL,
    parent_id bigint,
    description character varying(200) COLLATE pg_catalog."default",
    routerlink character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying
)
WITH (
    OIDS = FALSE
)